<?php

// exit if accessed directly
if (!defined('ABSPATH')) exit;

return apply_filters( 'gutslider_blocks', [
    [
        'name'        => 'content-slider',
        'title'       => __('Static', 'slider-blocks'),
        'description' => __('Create slider with static content like Image, text, button.', 'slider-blocks'),
        'is_pro'      => false,
        'demo_slug'   => 'static',
        'active'      => true,
    ],
    [
        'name'        => 'any-content',
        'title'       => __('Flexible', 'slider-blocks'),
        'description' => __('Create slider with any type of content.', 'slider-blocks'),
        'is_pro'      => false,
        'demo_slug'   => 'flexible',
        'active'      => true,
    ],
    [
        'name'        => 'testimonial-slider',
        'title'       => __('Testimonial', 'slider-blocks'),
        'description' => __('Create amazing testimonial slider.', 'slider-blocks'),
        'is_pro'      => false,
        'demo_slug'   => 'testimonial',
        'active'      => true,
    ],
    [
        'name'        => 'photo-carousel',
        'title'       => __('Photo Carousel', 'slider-blocks'),
        'description' => __('Create amazing photos carousel with lightbox.', 'slider-blocks'),
        'is_pro'      => false,
        'demo_slug'   => 'photo',
        'active'      => true,
    ],
    [
        'name'        => 'logo-carousel',
        'title'       => __('Brand Logos', 'slider-blocks'),
        'description' => __('Create clients logos carousel with amazing styles.', 'slider-blocks'),
        'is_pro'      => false,
        'demo_slug'   => 'brand-logos',
        'active'      => true,
    ],
    [
        'name'        => 'before-after',
        'title'       => __('Before After', 'slider-blocks'),
        'description' => __('Create photos comparision before after slider.', 'slider-blocks'),
        'is_pro'      => false,
        'demo_slug'   => 'before-after',
        'active'      => true,
    ],
    [
        'name'        => 'videos-carousel',
        'title'       => __('Videos', 'slider-blocks'),
        'description' => __('Create videos carousel from video sharing platform e.g YouTube', 'slider-blocks'),
        'is_pro'      => false,
        'demo_slug'   => 'videos',
        'active'      => true,
    ],
    [
        'name'        => 'post-slider',
        'title'       => __('Blog Post', 'slider-blocks'),
        'description' => __('Create dynamic content slider or carousel using blog posts.', 'slider-blocks'),
        'is_pro'      => false,
        'demo_slug'   => 'post-slider',
        'active'      => true,
    ],
    [
        'name'        => 'shader-slider',
        'title'       => __('Shader Slider', 'slider-blocks'),
        'description' => __('Interactive shader slider for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => 'shader-slider',
        'active'      => true,
    ],
    [
        'name'        => 'shutters-slider',
        'title'       => __('Shutters Slider', 'slider-blocks'),
        'description' => __('Interactive shutters slider for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => 'shutters-slider',
        'active'      => true,
    ],
    [
        'name'        => 'slicer-slider',
        'title'       => __('Slicer Slider', 'slider-blocks'),
        'description' => __('Interactive slicer slider for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => 'slicer-slider',
        'active'      => true,
    ],
    [
        'name'        => 'fashion-slider',
        'title'       => __('Fashion Slider', 'slider-blocks'),
        'description' => __('Interactive fashion slider for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => 'fashion-slider',
        'active'      => true,
    ],
    [
        'name'        => 'triple-slider',
        'title'       => __('Triple Slider', 'slider-blocks'),
        'description' => __('Interactive triple slider for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => 'triple-slider',
        'active'      => true,
    ],
    [
        'name'        => 'spring-carousel',
        'title'       => __('Spring Carousel', 'slider-blocks'),
        'description' => __('Interactive spring carousel for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => 'spring-carousel',
        'active'      => true,
    ],
    [
        'name'        => 'panorama-carousel',
        'title'       => __('Panorama Carousel', 'slider-blocks'),
        'description' => __('Interactive panorama carousel for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => 'panorama-carousel',
        'active'      => true,
    ],
    [
        'name'        => 'three-d-carousel',
        'title'       => __('3D Carousel', 'slider-blocks'),
        'description' => __('Interactive 3D carousel for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => '3d-carousel',
        'active'      => true,
    ],
    [
        'name'        => 'card-slider',
        'title'       => __('Card Slider', 'slider-blocks'),
        'description' => __('Interactive card slider for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => 'card-slider',
        'active'      => true,
    ],
    [
        'name'        => 'marquee-carousel',
        'title'       => __('Marquee Carousel', 'slider-blocks'),
        'description' => __('Interactive marquee carousel for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => 'marquee-carousel',
        'active'      => true,
    ],
    [
        'name'        => 'material-carousel',
        'title'       => __('Material Carousel', 'slider-blocks'),
        'description' => __('Interactive material carousel for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => 'material',
        'active'      => true,
    ],
    [
        'name'        => 'tinder-slider',
        'title'       => __('Tinder Slider', 'slider-blocks'),
        'description' => __('Interactive tinder slider for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => 'tinder-slider',
        'active'      => true,
    ],
    [
        'name'        => 'hover-slider',
        'title'       => __('Hover Slider', 'slider-blocks'),
        'description' => __('Interactive hover slider for static and dynamic content.', 'slider-blocks'),
        'is_pro'      => true,
        'demo_slug'   => 'hover-slider',
        'active'      => true,
    ],
    
] );